import { Ionicons } from '@expo/vector-icons';
import { useFocusEffect } from '@react-navigation/native';
import { useCallback, useState } from 'react';
import { ActivityIndicator, Alert, StyleSheet, Text, View } from 'react-native';
import { api, getApiError } from '../api/client';
import { Screen } from '../components/Screen';
import type { ApiResponse, Payment } from '../types/api';

export function PaymentHistoryScreen() {
  const [items, setItems] = useState<Payment[]>([]);
  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);

  const load = useCallback(async () => {
    try {
      const response = await api.get<ApiResponse<{ items: Payment[] }>>('/payments', { params: { page: 1, limit: 100 } });
      setItems(response.data.data.items);
    } catch (error) {
      Alert.alert('Unable to load payment history', getApiError(error));
    } finally {
      setLoading(false);
      setRefreshing(false);
    }
  }, []);

  useFocusEffect(useCallback(() => { void load(); }, [load]));

  const relatedText = (payment: Payment) => {
    if (payment.invoice) return `${payment.invoice.invoiceNumber} · ${payment.invoice.description}`;
    if (payment.eventBooking) return `${payment.eventBooking.event.title} · ${payment.eventBooking.ticketNumber}`;
    if (payment.roomBooking) return payment.roomBooking.bookingNumber;
    return payment.paymentType.replaceAll('_', ' ');
  };

  return (
    <Screen refreshing={refreshing} onRefresh={() => { setRefreshing(true); void load(); }}>
      <Text style={styles.title}>Payment history</Text>
      <Text style={styles.subtitle}>Invoice and booking transactions generated by the application.</Text>
      {loading ? <ActivityIndicator size="large" color="#175CD3" style={{ marginTop: 60 }} /> : items.map((payment) => (
        <View key={payment.id} style={styles.card}>
          <View style={[styles.icon, payment.status === 'REFUNDED' && styles.refundIcon]}>
            <Ionicons name={payment.status === 'REFUNDED' ? 'return-down-back-outline' : 'checkmark-outline'} size={21} color={payment.status === 'REFUNDED' ? '#C4320A' : '#027A48'} />
          </View>
          <View style={styles.content}>
            <Text style={styles.related} numberOfLines={2}>{relatedText(payment)}</Text>
            <Text style={styles.transaction}>{payment.transactionId}</Text>
            <Text style={styles.meta}>{payment.paymentMethod} · {new Date(payment.paidAt).toLocaleString()}</Text>
          </View>
          <View style={styles.amountWrap}>
            <Text style={styles.amount}>₹{payment.amount.toLocaleString('en-IN')}</Text>
            <Text style={[styles.status, payment.status === 'REFUNDED' && styles.refundText]}>{payment.status}</Text>
          </View>
        </View>
      ))}
      {!loading && items.length === 0 && <View style={styles.empty}><Ionicons name="wallet-outline" size={42} color="#98A2B3" /><Text style={styles.emptyTitle}>No payments yet</Text><Text style={styles.emptyText}>Successful simulated transactions will appear here.</Text></View>}
    </Screen>
  );
}

const styles = StyleSheet.create({
  title: { color: '#101828', fontSize: 26, fontWeight: '900', marginTop: 4 },
  subtitle: { color: '#667085', fontSize: 14, lineHeight: 21, marginTop: 5, marginBottom: 5 },
  card: { backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#EAECF0', borderRadius: 17, padding: 15, marginTop: 13, flexDirection: 'row', alignItems: 'flex-start', gap: 11 },
  icon: { width: 40, height: 40, borderRadius: 13, backgroundColor: '#ECFDF3', alignItems: 'center', justifyContent: 'center' },
  refundIcon: { backgroundColor: '#FFF6ED' },
  content: { flex: 1 },
  related: { color: '#101828', fontSize: 12, fontWeight: '900', lineHeight: 17 },
  transaction: { color: '#175CD3', fontSize: 8, fontWeight: '800', marginTop: 5 },
  meta: { color: '#98A2B3', fontSize: 9, marginTop: 4 },
  amountWrap: { alignItems: 'flex-end' },
  amount: { color: '#101828', fontSize: 14, fontWeight: '900' },
  status: { color: '#027A48', fontSize: 8, fontWeight: '900', marginTop: 5 },
  refundText: { color: '#C4320A' },
  empty: { marginTop: 35, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#EAECF0', borderRadius: 20, alignItems: 'center', padding: 30 },
  emptyTitle: { color: '#344054', fontSize: 17, fontWeight: '900', marginTop: 12 },
  emptyText: { color: '#667085', marginTop: 5, textAlign: 'center' },
});
